# Generated by Django 5.0 on 2024-02-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('bi', models.ImageField(upload_to='images/')),
                ('cname', models.CharField(max_length=200)),
                ('cinfo', models.CharField(max_length=400)),
                ('cimg', models.ImageField(upload_to='images/')),
                ('cname1', models.CharField(max_length=200)),
                ('cinfo1', models.CharField(max_length=400)),
                ('cimg1', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='emplloye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=20)),
                ('empno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
    ]
