# Generated by Django 5.0 on 2024-01-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
    ]
