# Generated by Django 5.0 on 2024-02-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cimg1',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cinfo1',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AlterField(
            model_name='course',
            name='cname1',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
