# Generated by Django 5.0 on 2024-02-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0002_alter_course_cimg1_alter_course_cinfo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
