# Generated by Django 5.0 on 2024-01-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
