# Generated by Django 5.0 on 2024-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0005_alter_course_duration_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bi',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='cimg',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='cinfo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='cname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
