# Generated by Django 5.0 on 2024-02-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0007_alter_course_cimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bi',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
