# Generated by Django 5.0 on 2024-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0008_alter_course_bi'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cinfo1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='cname1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='img1',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
