# Generated by Django 5.0 on 2024-02-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0011_alter_course_cinfo1_alter_course_cname1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cinfo1',
            field=models.CharField(default='A', max_length=200),
        ),
    ]
