# Generated by Django 5.0 on 2024-02-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0014_alter_course_cinfo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cinfo1',
            field=models.CharField(default=None, max_length=200, verbose_name='cinfo1'),
        ),
    ]
