# Generated by Django 5.0 on 2024-02-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0015_alter_course_cinfo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cinfo1',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
