# Generated by Django 5.0 on 2024-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0016_alter_course_cinfo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cinfo1',
        ),
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
