# Generated by Django 5.0 on 2024-02-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0017_remove_course_cinfo1_course_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='info',
        ),
    ]
