# Generated by Django 5.0 on 2024-02-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0019_remove_course_cname1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img1',
        ),
    ]
