# Generated by Django 5.0 on 2024-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0020_remove_course_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cinfo',
            field=models.CharField(max_length=400),
        ),
    ]
