# Generated by Django 5.0 on 2024-02-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0021_alter_course_cinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
