# Generated by Django 5.0 on 2024-02-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sega', '0022_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='img',
        ),
    ]
